export const OVERTIME_FIRST_TIER_HOURS = 120;
export const OVERTIME_MAX_HOURS_YEAR = 150;
export const OVERTIME_SURCHARGE_FIRST = 0.40;
export const OVERTIME_SURCHARGE_EXCESS = 0.60;
export const SIXTH_DAY_SURCHARGE = 0.40;
export const SIXTH_DAY_MAX_HOURS = 8;
export const DEFAULT_WEEKLY_HOURS_PENTHIMERO = 40;
export const DEFAULT_WEEKLY_HOURS_EXAHIMERO = 48;
